language: python
cache: pip
sudo: false

python:
  - 2.7
  - 3.5

env:
  - PANDAS_VERSION=0.18.1
    NUMPY_VERSION=1.11.3
  - PANDAS_VERSION=0.23.4
    NUMPY_VERSION=1.15.2

before_install:
  - wget "https://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-4.3.30-Linux-x86_64.sh" -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no

install:
  - conda create -n testenv --yes -c quantopian pip python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION pandas=$PANDAS_VERSION
  - source activate testenv
  - python -m pip install --upgrade pip coveralls
  - python -m pip install -r etc/requirements.txt
  - python -m pip freeze | sort

script:
  - flake8 trading_calendars tests
  - nosetests tests

after_success:
  - coveralls

notifications:
  email: false

branches:
  only:
    - master
